#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
module load R
# adonis using data from open silva for sample depth weighted
echo 'adonis for sample depth from openreference silva weighted'
time compare_categories.py --method adonis -i ~/paperdata2/cd_closedsilva13.2_chimera/bdiv_even8443/unweighted_unifrac_dm.txt \
-m ~/paperdata2/validate_map6/map_merged6.tsv_corrected.txt \
-c Population -o ~/paperdata2/statistical_analysis/adonis_population_chimera_unweighted -n 999
# deactivating environment
source deactivate
