#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# distance matrix population density
echo 'distance matrix population density'
time distance_matrix_from_mapping.py -i ~/paperdata2/validate_map6/map_merged6.tsv_corrected.txt -c Population \
-o map_distance_matrix_population.txt
# deactivating environment
source deactivate
