#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# joining Illumina sequences
echo "join paired ends"
time join_paired_ends.py -m SeqPrep -b Index.fastq.gz -f Read1.fastq.gz -r Read2.fastq.gz -o joined_paired_ends_Seqprep
# deactivating environment
source deactivate
