#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Chimera checking
echo 'chimera checking with usearch 6.1'
time identify_chimeric_seqs.py -m usearch61 \
-i ~/2018_02_smb/demultiplexing2/seqs.fna \
-r ~/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-o ~/2018_02_smb/usearch_chimera_checking/
# deactivating environment
source deactivate
