#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# filtering with chimeras
echo 'filtering with chimeras'
time filter_fasta.py -f ~/2018_02_smb/demultiplexing2/seqs.fna \
-o ~/2018_02_smb/filterout/seqs_chimeras_filtered.fna -s usearch_chimera_checking/chimeras.txt -n
# deactivating environment
source deactivate
