#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with closed reference silva 13.2 chimera"
time pick_closed_reference_otus.py -i ~/2018_02_smb/filterout/seqs_chimeras_filtered.fna \
-r ~/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-t ~/SILVA_132_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt \
-o ~/2018_02_smb/otusclosed_silva13.2_chimera -a -O 16
# deactivating environment
source deactivate
