#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# core diversity
echo "Core diversity for closed reference silva 13.2"
time core_diversity_analyses.py --recover_from_failure \
-i ~/2018_02_smb/otusclosed_silva13.2_chimera/otu_table.biom \
-m ~/2018_02_smb/map_complete.tsv \
-t ~/SILVA_132_QIIME_release/trees/97/97_otus.tre \
-e 36064 \
-o ~/2018_02_smb/cd_closedsilva13.2_chimera
# deactivating environment
source deactivate
