#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
module load R
# ADONIS using data from closed silva for sample moisture unweighted
echo 'ADONIS for sample moisture from closed silva unweighted'
time compare_categories.py --method adonis \
-i ~/2018_02_smb/cd_closedsilva13.2_chimera/bdiv_even36064/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map_complete.tsv -c SampleMoisture \
-o ~/2018_02_smb/ADONIS_chimera/unweighted/adonis_moisture_unweighted -n 999
# ADONIS using data from closed silva for sample Ph unweighted
echo 'ADONIS for sample Ph from closed silva unweighted'
time compare_categories.py --method adonis \
-i ~/2018_02_smb/cd_closedsilva13.2_chimera/bdiv_even36064/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map_complete.tsv -c SamplePh \
-o ~/2018_02_smb/ADONIS_chimera/unweighted/adonis_Ph_unweighted -n 999
# ADONIS using data from closed silva for sample potassium unweighted
echo 'ADONIS for sample potassium closed silva unweighted'
time compare_categories.py --method adonis \
-i ~/2018_02_smb/cd_closedsilva13.2_chimera/bdiv_even36064/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map_complete.tsv -c SamplePotassium \
-o ~/2018_02_smb/ADONIS_chimera/unweighted/adonis_Potassium_unweighted -n 999
# ADONIS using data from closed silva for sample phosphorus unweighted
echo 'ADONIS for sample phosphorus from closed silva unweighted'
time compare_categories.py --method adonis \
-i ~/2018_02_smb/cd_closedsilva13.2_chimera/bdiv_even36064/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map_complete.tsv -c SamplePhosphorus \
-o ~/2018_02_smb/ADONIS_chimera/unweighted/adonis_Phosphorus_unweighted -n 999
# ADONIS using data from closed silva for sample nitrogen unweighted
echo 'ADONIS for sample nitrogen from closed silva unweighted'
time compare_categories.py --method adonis \
-i ~/2018_02_smb/cd_closedsilva13.2_chimera/bdiv_even36064/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map_complete.tsv -c SampleNitrogen \
-o ~/2018_02_smb/ADONIS_chimera/unweighted/adonis_nitrogen_unweighted -n 999
