#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
module load R
# BIO-ENV using data from open silva for sample depth and Ph weighted
echo 'BIO-ENV  for sample depth and Ph from openreference silva weighted'
time compare_categories.py --method bioenv -i ~/2018_02_smb/core_diversity/cd_opensilva/bdiv_even745/weighted_unifrac_dm.txt -m ~/2018_02_smb/map_complete.tsv -c SampleDepth,SamplePh -o ~/2018_02_smb/statistical_analyses/BIOENV/bioenv_depth_Ph_opensilva_weighted -n 999
# BIO-ENV using data from open silva for sample latitude and Ph weighted
echo 'BIO-ENV  for sample latitude and Ph from openreference silva weighted'
time compare_categories.py --method bioenv -i ~/2018_02_smb/core_diversity/cd_opensilva/bdiv_even745/weighted_unifrac_dm.txt -m ~/2018_02_smb/map_complete.tsv -c SampleLatitude,SamplePh -o ~/2018_02_smb/statistical_analyses/BIOENV/bioenv_latitude_Ph_opensilva_weighted -n 999
# BIO-ENV using data from open silva for sample longitude and Ph weighted
echo 'BIO-ENV  for sample longitude and Ph from openreference silva weighted'
time compare_categories.py --method bioenv -i ~/2018_02_smb/core_diversity/cd_opensilva/bdiv_even745/weighted_unifrac_dm.txt -m ~/2018_02_smb/map_complete.tsv -c SampleLongitude,SamplePh -o ~/2018_02_smb/statistical_analyses/BIOENV/bioenv_longitude_Ph_opensilva_weighted -n 999
# deactivating environment
source deactivate
