#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Chimera checking
echo 'chimera checking open silva with usearch 6.1'
time identify_chimeric_seqs.py -m usearch61 \
-i ~/paperdata2/seqs_merged.fna \
-r ~/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-o ~/paperdata2/usearch_chimera_checking/
# deactivating environment
source deactivate
