#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with closed reference gn"
time pick_closed_reference_otus.py -i ~/2018_02_smb/demultiplexing1/seqs.fna.incomplete -o ~/2018_02_smb/otusclosedgn -a -O 16
# deactivating environment
source deactivate
