#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with closed reference"
time pick_closed_reference_otus.py -i ~/2018_02_smb/demultiplexing2/seqs.fna -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -o ~/2018_02_smb/otusclosed_silva2 -a -O 16
# deactivating environment
source deactivate
