#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# compare alpha diversity
echo 'compare alpha diversity population'
time compare_alpha_diversity.py -i ~/paperdata2/cd_closedsilva_3/arare_max8476/alpha_div_collated/PD_whole_tree.txt \
-m ~/paperdata2/validate_map6/map_merged6.tsv_corrected.txt \
-c Population -p fdr -o ~/paperdata2/compare_alpha_population
# deactivating environment
source deactivate
