#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# core diversity
echo "Core diversity for open reference silva"
time core_diversity_analyses.py --recover_from_failure -i ~/2018_02_smb/otusopen_silva2/ otu_table_mc2_w_tax_no_pynast_failures.biom -m ~/2018_02_smb/map_complete.tsv -t ~/2018_02_smb/otusopen_silva2/rep_set.tre -e 745 -o ~/2018_02_smb/cd_opensilva
# deactivating environment
source deactivate
