#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# core diversity
echo "Core diversity for closed reference gn"
time core_diversity_analyses.py --recover_from_failure -i ~/2018_02_smb/otusclosedgn2/otu_table.biom -m ~/2018_02_smb/map_complete.tsv -t ~/2018_02_smb/otusclosedgn2/97_otus.tree -e 605 -o ~/2018_02_smb/cd_closedgn
# deactivating environment
source deactivate
