#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# group significance
echo 'group significance'
time group_significance.py -i ~/paperdata2/otusclosed_silva13.2/otu_table.biom \
-m ~/paperdata2/validate_map6/map_merged6.tsv_corrected.txt \
-c Population -s kruskal_wallis -o group_significance/kw_ocs.txt
# deactivating environment
source deactivate
