#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with open reference silva 13.2"
time pick_open_reference_otus.py -i ~/2018_02_smb/demultiplexing2/seqs.fna \
-r ~/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-o ~/2018_02_smb/OTUS/otusopen_silva13.2 -a -O 16
# deactivating environment
source deactivate
